version: 0.2


phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPO_URL=707742534627.dkr.ecr.us-east-1.amazonaws.com/multiloja/apache-dev
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - echo started build $(date "+%F | %R")
      - echo build docker image...
      - docker build . --tag $REPO_URL:$IMAGE_TAG
      - docker images $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo build complete $(date "+%F | %R")
      - echo pushing image docker to repository...
      - docker push $REPO_URL:$IMAGE_TAG
      - printf '[{"name":"multiloja-apache","imageUri":"%s"}]' $REPO_URL:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
